<a href="https://colab.research.google.com/github/dilaraesmer/The-Data-Analyst-Course-Complete-Data-Analyst-Bootcamp-2023/blob/main/Example_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Packages

In [ ]:
import numpy as np
import csv

Importing the Data

In [ ]:
with open('Features.csv', 'r') as f:
    reader = csv.reader(f)
    for i, row in enumerate(reader):
        try:
            # process the row
            print(row)  # Example of processing the row
        except ValueError:
            # handle the error
           print(f"Error on line {i+1}")

['id', 'name', 'duration', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'danceability']
['0VjIjW4GlUZAMYd2vXMi3b', 'Blinding Lights', '3.33', '0.73', '1', '-5.934', '1', '0.0598', '0.00146', '9.54e-05', '0.0897', '0.334', '171.005', '0.514']
['7qiZfU4dY1lWllzX7mPBI3', 'Shape of You', '3.9', '0.652', '1', '-3.183', '0', '0.0802', '0.581', '0.0', '0.0931', '0.931', '95.977', '0.825']
['2XU0oxnq2qxCpomAAuJY8K', 'Dance Monkey', '3.49', '0.588', '6', '-6.4', '0', '0.0924', '0.692', '0.000104', '0.149', '0.513', '98.027', '0.824']
['7qEHsqek33rTcFNT9PFqLf', 'Someone You Loved', '3.04', '0.405', '1', '-5.679', '1', '0.0319', '0.751', '0.0', '0.105', '0.446', '109.891', '0.501']
['0e7ipj03S05BNilyu5bRzt', 'Rockstar', '3.64', '0.52', '5', '-6.136', '0', '0.0712', '0.124', '7.01e-05', '0.131', '0.129', '159.801', '0.585']
['3KkXRkHbMCARz0aVfEt68P', 'Sunflower', '2.63', '0.479', '2', '-5.574', '1', '0.0466', '0.556', '0.0', '0.0703', '0.913', '89.911', '0.76']
['1zi7xx7UVEFkmKfv06H8x0', 'One Dance', '2.9', '0.625', '1', '-5.609', '1', '0.0536', '0.00776', '0.0018', '0.329', '0.37', '103.967', '0.792']
['7BKLCZ1jbUBVqRi2FVlTVw', 'Closer', '4.08', '0.524', '8', '-5.599', '1', '0.0338', '0.414', '0.0', '0.111', '0.661', '95.01', '0.748']
['789CxjEOtO76BVD1A9yJQH', 'Stay', '4.01', '0.31', '9', '-10.164', '0', '0.0283', '0.945', '6.12e-05', '0.117', '0.125', '111.893', '0.621']
['0pqnGHJpmpxLKifKRmU6WP', 'Believer', '3.41', '0.78', '10', '-4.374', '0', '0.128', '0.0622', '0.0', '0.081', '0.666', '124.949', '0.776']
['6v3KW9xbzN5yKLt9YKDYA2', 'Se√±orita', '3.18', '0.548', '9', '-6.049', '0', '0.029', '0.0392', '0.0', '0.0828', '0.749', '116.967', '0.759']
['41P6Tnd8KIHqON0QIydx6a', 'Perfect', '2.96', '0.663', '11', '-6.818', '1', '0.0331', '0.433', '0.124', '0.102', '0.6', '146.053', '0.634']
['02MWAaffLxlfxAUY7c5dvx', 'Heat Waves', '3.98', '0.525', '11', '-6.9', '1', '0.0944', '0.44', '6.7e-06', '0.0921', '0.531', '80.87', '0.761']
['5uCax9HTNlzGybIStD3vDh', "Say You Won't Let Go", '3.52', '0.557', '10', '-7.398', '1', '0.059', '0.695', '0.0', '0.0902', '0.494', '85.043', '0.358']
['7MXVkk9YMctZqd1Srtv4MB', 'Starboy', '3.84', '0.587', '7', '-7.015', '1', '0.276', '0.141', '6.35e-06', '0.137', '0.486', '186.003', '0.679']
['2Fxmhks0bxGSBdJ92vM42m', 'Bad Guy', '3.23', '0.425', '7', '-10.965', '1', '0.375', '0.328', '0.13', '0.1', '0.562', '135.128', '0.701']
['0UduxLm2YxJcRMMX1K6E7E', 'Thinking Out Loud', '4.69', '0.445', '2', '-6.061', '1', '0.0296', '0.474', '0.0', '0.184', '0.591', '78.997', '0.781']
['285pBltuF7vW8TeWk8hdRR', 'Lucid Dreams', '4.0', '0.566', '6', '-7.23', '0', '0.2', '0.349', '0.0', '0.34', '0.218', '83.903', '0.511']
['6o6urrgOIVbIzzmO4KJHCO', "Don't Start Now", '3.02', '0.185', '11', '-12.205', '0', '0.0484', '0.876', '0.459', '0.237', '0.707', '78.775', '0.498']
['0u2P5u6lvoDfwTYjAADbn4', 'Lovely', '3.34', '0.296', '4', '-10.109', '0', '0.0333', '0.934', '0.0', '0.095', '0.12', '115.284', '0.351']
['6UelLqGlWMcVH1E5c4H7lY', 'Watermelon Sugar', '2.9', '0.816', '0', '-4.209', '1', '0.0465', '0.122', '0.0', '0.335', '0.557', '95.39', '0.548']
['6DCZcSspjsKoFjzjrWoCdn', "God's Plan", '3.32', '0.449', '7', '-9.211', '1', '0.109', '0.0332', '8.29e-05', '0.552', '0.357', '77.169', '0.754']
['4cj6Ti4wOXZ5ZdWlUZxRSP', 'Photograph', '4.32', '0.379', '4', '-10.48', '1', '0.0359', '0.607', '0.000472', '0.0986', '0.22', '108.033', '0.718']
['7tFiyTwD0nx5a1eklYtX2J', 'Bohemian Rhapsody', '5.91', '0.402', '0', '-9.961', '0', '0.0536', '0.288', '0.0', '0.243', '0.228', '143.883', '0.392']
['6RUKPb4LETWmmr3iAEQktW', 'Something Just Like This', '4.12', '0.635', '11', '-6.769', '0', '0.0317', '0.0498', '1.44e-05', '0.164', '0.446', '103.019', '0.617']
['2QjOHCTQ1Jl3zawyYOpxh6', 'Sweater Weather', '4.01', '0.807', '10', '-2.81', '1', '0.0336', '0.0495', '0.0177', '0.101', '0.398', '124.053', '0.612']
['2VxeLyX666F8uXCJ0dZF8B', 'Shallow', '3.6', '0.385', '7', '-6.362', '1', '0.0308', '0.371', '0.0', '0.231', '0.323', '95.799', '0.572']
['4LRPiXqCikLlN15c3yImP7', 'As It Was', '2.79', '0.731', '6', '-5.338', '0', '0.0557', '0.342', '0.00101', '0.311', '0.662', '173.93', '0.52']
['50kpGaPAhYJ3sGmk6vplg0', 'Love Yourself', '3.9', '0.378', '4', '-9.828', '1', '0.438', '0.835', '0.0', '0.28', '0.515', '100.418', '0.609']
['21jGcNKet2qwijlDFuPiPb', 'Circles', '3.59', '0.762', '0', '-3.497', '1', '0.0395', '0.192', '0.00244', '0.0863', '0.553', '120.042', '0.695']
['3ee8Jmje8o58CHK66QrVC2', 'Sad!', '2.78', '0.613', '8', '-4.88', '1', '0.145', '0.258', '0.00372', '0.123', '0.473', '75.023', '0.74']
['1CS7Sd1u5tWkstBhpssyjP', 'Take Me to Church', '4.03', '0.664', '4', '-5.303', '0', '0.0464', '0.634', '0.0', '0.116', '0.437', '128.945', '0.566']
['3U4isOIWM3VvDubwSI3y7a', 'All of Me', '4.49', '0.264', '8', '-7.064', '1', '0.0322', '0.922', '0.0', '0.132', '0.331', '119.93', '0.422']
['57bgtoPSgt236HzfBOd8kj', 'Thunder', '4.88', '0.89', '4', '-5.175', '1', '0.0364', '0.000147', '0.0117', '0.217', '0.259', '133.52', '0.502']
['6ocbgoVGwYJhOv1GgI9NsF', '7 Rings', '2.98', '0.317', '1', '-10.732', '0', '0.334', '0.592', '0.0', '0.0881', '0.327', '140.048', '0.778']
['6gBFPUFcJLzWGx4lenP6h2', 'Goosebumps', '4.06', '0.728', '7', '-3.37', '1', '0.0484', '0.0847', '0.0', '0.149', '0.43', '130.049', '0.841']
['7m9OqQk4RVRkw9JJdeAw96', 'Jocelyn Flores', '1.99', '0.391', '0', '-9.144', '0', '0.242', '0.469', '4.13e-06', '0.297', '0.437', '134.021', '0.872']
['1rfofaqEpACxVEHIZBJe6W', 'Havana', '3.62', '0.523', '2', '-4.333', '1', '0.03', '0.184', '3.56e-05', '0.132', '0.394', '104.988', '0.765']
['3CRDbSIZ4r5MsZ0YwxuEkn', 'Stressed Out', '3.37', '0.637', '4', '-5.677', '0', '0.141', '0.0462', '2.29e-05', '0.0602', '0.648', '169.977', '0.734']
['7GX5flRQZVHRAGd6B4TmDO', 'XO Tour Llif3', '3.05', '0.75', '11', '-6.366', '0', '0.231', '0.00264', '0.0', '0.109', '0.401', '155.096', '0.732']
['6sy3LkhNFjJWlaeSMNwQ62', 'Counting Stars', '4.3', '0.705', '1', '-4.972', '0', '0.0382', '0.0654', '0.0', '0.115', '0.477', '122.017', '0.664']
['67WK7JasAfTIDXs8ofPqx1', 'New Rules', '3.49', '0.7', '9', '-6.021', '0', '0.0694', '0.00265', '1.55e-05', '0.153', '0.608', '116.078', '0.762']
['0nrRP2bk19rLc0orkWPQk2', 'Wake Me Up', '4.12', '0.783', '2', '-5.697', '1', '0.0523', '0.0038', '0.0012', '0.161', '0.643', '124.08', '0.532']
['3JvrhDOgAt6p7K8mDyZwRd', 'Riptide', '3.4', '0.731', '1', '-6.694', '1', '0.0379', '0.431', '0.0', '0.151', '0.51', '101.654', '0.484']
['0O6u0VJ46W86TxN9wgyqDj', 'Happier', '3.21', '0.67', '5', '-6.009', '1', '0.0751', '0.121', '0.0', '0.121', '0.472', '100.964', '0.733']
['7KXjTSCq5nL1LoYtL7XAwS', 'Humble', '2.95', '0.621', '1', '-6.638', '0', '0.102', '0.000282', '5.39e-05', '0.0958', '0.421', '150.011', '0.908']
['1KxwZYyzWNyZSRyErj2ojT', 'Let Her Go', '4.21', '0.545', '7', '-7.346', '1', '0.0688', '0.365', '0.0', '0.0963', '0.243', '74.897', '0.479']
['7fBv7CLKzipRk6EC6TWHOB', 'The Hills', '4.04', '0.564', '0', '-7.063', '0', '0.0515', '0.0671', '0.0', '0.135', '0.137', '113.003', '0.585']
['2xLMifQCjDGFmkHkpNLD9h', 'Sicko Mode', '5.21', '0.73', '8', '-3.714', '1', '0.222', '0.00513', '0.0', '0.124', '0.446', '155.008', '0.834']
['7GRu6XaTVRIdV4E0Ty4QGX', "Can't Hold Us", '1.52', '0.871', '10', '-6.351', '1', '0.0752', '0.000744', '0.00498', '0.253', '0.219', '128.044', '0.556']
['4ZtFanR9U6ndgddUvNcjcG', 'Good 4 U', '2.97', '0.664', '9', '-5.044', '1', '0.154', '0.335', '0.0', '0.0849', '0.688', '166.928', '0.563']
['4VHkjPgAis9JNfc1URn7zZ', 'Sorry', '3.1', '0.643', '6', '-7.811', '0', '0.0984', '8.47e-05', '0.0', '0.203', '0.492', '141.961', '0.73']
['7ef4DlsgrMEH11cDZd32M6', 'One Kiss', '3.58', '0.862', '9', '-3.24', '0', '0.11', '0.037', '2.19e-05', '0.0814', '0.592', '123.994', '0.791']
['0lYBSQXN6rCTvUZvg9S0lU', 'Let Me Love You', '3.43', '0.716', '8', '-5.371', '1', '0.0349', '0.0863', '2.63e-05', '0.135', '0.163', '99.988', '0.649']
['5wANPM4fQCJwkGd4rN57mH', 'Drivers License', '4.03', '0.431', '10', '-8.81', '1', '0.0578', '0.768', '1.42e-05', '0.106', '0.137', '143.875', '0.561']
['1Lim1Py7xBgbAkAys3AGAG', 'Lean On', '2.94', '0.809', '7', '-3.081', '0', '0.0625', '0.00346', '0.00123', '0.565', '0.274', '98.007', '0.723']
['3QGsuHI8jO1Rx4JWLUh9jd', 'Treat You Better', '3.13', '0.819', '10', '-4.078', '0', '0.341', '0.106', '0.0', '0.107', '0.747', '82.695', '0.444']
['0zLCBJZSiELJf02ucPP9wb', 'Roses (Imanbek remix)', '2.95', '0.719', '8', '-5.472', '1', '0.0474', '0.0143', '0.00777', '0.359', '0.863', '121.955', '0.769']
['7dt6x5M1jzdTEt8oCbisTK', 'Better Now', '3.85', '0.578', '10', '-5.804', '1', '0.04', '0.331', '0.0', '0.135', '0.341', '145.038', '0.68']
['5Nm9ERjJZ5oyfXZTECKmRt', 'Stay with Me', '2.88', '0.42', '0', '-6.444', '1', '0.0414', '0.588', '6.39e-05', '0.11', '0.184', '84.094', '0.418']
['3a1lNhkSLSkpJE4MSHpDu9', 'Congratulations', '3.67', '0.804', '6', '-4.183', '1', '0.0363', '0.215', '0.0', '0.253', '0.492', '123.146', '0.63']
['698ItKASDavgwZ3WjaWjtz', 'Faded', '3.54', '0.627', '6', '-5.085', '1', '0.0476', '0.0281', '7.97e-06', '0.11', '0.159', '179.642', '0.468']
['7lQ8MOhq6IN2w8EYcFNSUk', 'Without Me', '4.84', '0.669', '7', '-2.827', '1', '0.0738', '0.00286', '0.0', '0.237', '0.662', '112.238', '0.908']
['27NovPIUIRrOZoCHxABJwK', 'Industry Baby', '3.53', '0.704', '3', '-7.409', '0', '0.0615', '0.0203', '0.0', '0.0501', '0.894', '149.995', '0.736']
['5Z01UMMf7V1o0MzF86s6WJ', 'Lose Yourself', '5.44', '0.744', '2', '-4.565', '1', '0.257', '0.00868', '0.000423', '0.359', '0.0612', '171.374', '0.692']
['5UXJzLFdBn6u9FJTCnoHrH', 'Memories', '4.15', '0.684', '11', '-6.306', '1', '0.044', '0.00979', '0.0', '0.348', '0.556', '112.969', '0.34']
['3LlAyCYU26dvFZBDUIMb7a', 'Demons', '2.92', '0.71', '3', '-3.015', '1', '0.0321', '0.19', '0.00025', '0.329', '0.428', '89.938', '0.505']
['003vvx7Niy0yvhvHt4a68B', 'Mr. Brightside', '3.72', '0.911', '1', '-5.23', '1', '0.0747', '0.00121', '0.0', '0.0995', '0.236', '148.033', '0.352']
['32OlwWuMpZ6b0aN2RZOeMS', 'Uptown Funk', '4.49', '0.609', '0', '-7.223', '1', '0.0824', '0.00801', '8.15e-05', '0.0344', '0.928', '114.988', '0.856']
['3VlbOrM6nYPprVvzBZllE5', 'Too Good at Goodbyes', '3.35', '0.372', '5', '-8.237', '1', '0.0432', '0.64', '0.0', '0.169', '0.476', '91.873', '0.681']
['5nujrmhLynf4yMoMtj8AQF', 'Levitating', '3.38', '0.825', '6', '-3.787', '0', '0.0601', '0.00883', '0.0', '0.0674', '0.915', '102.977', '0.702']
['1MtUq6Wp1eQ8PC6BbPCj8P', 'I Took a Pill in Ibiza\xa0(Seeb\xa0Remix)', '3.3', '0.714', '7', '-6.645', '0', '0.111', '0.0353', '8.42e-06', '0.0843', '0.71', '101.969', '0.664']
['40XeGNGFchGYw7y0ue1GiG', "Don't Let Me Down", '3.49', '0.502', '4', '-7.539', '1', '0.0493', '0.699', '0.000156', '0.094', '0.674', '163.347', '0.455']
['3e9HZxeyfWwjeyPAMmWSSQ', 'Thank U, Next', '3.46', '0.653', '1', '-5.634', '1', '0.0658', '0.229', '0.0', '0.101', '0.412', '106.966', '0.717']
['3An0Mae1vtOmLpQtqD4ynf', "I Don't Care", '3.67', '0.676', '6', '-5.041', '1', '0.0442', '0.0902', '0.0', '0.0894', '0.843', '101.956', '0.798']
['47EiUVwUp4C9fGccaPuUCS', 'Dakiti', '3.42', '0.573', '4', '-10.059', '0', '0.0544', '0.401', '5.22e-05', '0.113', '0.145', '109.928', '0.731']
['1SC5rEoYDGUK4NfG82494W', 'Montero (Call Me by Your Name)', '2.3', '0.503', '8', '-6.725', '0', '0.22', '0.293', '0.0', '0.405', '0.71', '178.781', '0.593']
['0yUaLqhsVsguBpoOPL4cO7', 'Mood', '2.16', '0.74', '0', '-6.595', '1', '0.336', '0.696', '6.81e-06', '0.23', '0.532', '141.059', '0.768']
['5FVd6KXrgO9B3JPmC8OPst', 'Do I Wanna Know?', '4.54', '0.532', '5', '-7.596', '1', '0.0323', '0.186', '0.000263', '0.217', '0.405', '85.03', '0.548']
['3B54sVLJ402zGa6Xm4YGNe', 'Unforgettable', '3.9', '0.769', '6', '-5.043', '1', '0.123', '0.0293', '0.0101', '0.104', '0.733', '97.985', '0.726']
['2CEgGE6aESpnmtfiZwYlbV', 'Dynamite', '3.38', '0.783', '4', '-3.724', '1', '0.0859', '0.00379', '0.0', '0.036', '0.816', '119.975', '0.751']
['6rPO02ozF3bM7NnOV4h6s2', 'Despacito (remix)', '3.81', '0.816', '2', '-4.353', '1', '0.167', '0.228', '0.0', '0.0967', '0.816', '178.085', '0.653']
['0JP9xo3adEtGSdUEISiszL', 'Moonlight', '2.25', '0.537', '9', '-5.723', '0', '0.0804', '0.556', '0.00404', '0.102', '0.711', '128.009', '0.921']
['7ygpwy2qP3NbrxVkHvUhXY', 'Wonderwall', '4.31', '0.893', '2', '-4.097', '1', '0.0406', '0.000509', '0.0', '0.187', '0.434', '174.323', '0.375']
['68Dni7IE4VyPkTOH9mRWHr', 'No Role Modelz', '4.88', '0.521', '10', '-8.492', '0', '0.339', '0.324', '0.0', '0.0534', '0.494', '100.028', '0.69']
['0KKkJNfGyhkQ5aFogxQAPU', "That's What I Like", '3.44', '0.56', '1', '-4.961', '1', '0.0406', '0.013', '0.0', '0.0944', '0.86', '134.066', '0.853']
['0nbXyq5TXYPCO7pr3N8S4I', 'The Box', '3.28', '0.586', '10', '-6.687', '0', '0.0559', '0.104', '0.0', '0.79', '0.642', '116.971', '0.896']
['4xkOaSrkexMciUUogZKVTS', "'Till I Collapse", '4.96', '0.847', '1', '-3.237', '1', '0.186', '0.0622', '0.0', '0.0816', '0.1', '171.447', '0.548']
['7JJmb5XwzOO8jgpou264Ml', "There's Nothing Holdin' Me Back", '3.32', '0.813', '11', '-4.063', '0', '0.0554', '0.38', '0.0', '0.0779', '0.969', '121.998', '0.866']
['5jsw9uXEGuKyJzs0boZ1bT', 'Stitches', '3.45', '0.754', '1', '-6.684', '1', '0.0615', '0.0151', '0.0', '0.0486', '0.755', '149.789', '0.752']
['3S4px9f4lceWdKf0gWciFu', 'Cheap Thrills', '3.53', '0.698', '6', '-5.608', '0', '0.105', '0.0472', '0.00143', '0.0907', '0.732', '89.976', '0.628']
['5ghIJDpPoe3CfHMGu71E6T', 'Smells Like Teen Spirit', '5.03', '0.912', '1', '-4.556', '1', '0.0564', '2.55e-05', '0.000173', '0.106', '0.72', '116.761', '0.502']
['7KA4W4McWYRpgf0fWsJZWB', 'See You Again', '3.01', '0.559', '6', '-9.222', '1', '0.0959', '0.371', '7.49e-06', '0.109', '0.62', '78.558', '0.558']
['52ZAsLhFwhCZsExUpSdG5H', "I'm Yours", '2.93', '0.633', '1', '-6.726', '1', '0.0711', '0.0886', '0.0', '0.116', '0.505', '94.875', '0.646']
['0EcQcdcbQeVJn9fknj44Be', 'I Like Me Better', '3.29', '0.505', '9', '-7.621', '1', '0.255', '0.534', '2.58e-06', '0.104', '0.419', '91.972', '0.753']
['5kqIPrATaCc2LqxVWzQGbk', '7 Years', '3.96', '0.473', '10', '-5.829', '1', '0.0514', '0.287', '0.0', '0.391', '0.34', '119.992', '0.765']
['3AJwUDP919kvQ9QcozQPxg', 'Yellow', '4.45', '0.661', '11', '-7.227', '1', '0.0281', '0.00239', '0.000121', '0.234', '0.285', '173.372', '0.429']
['6UelLqGlWMcVH1E5c4H7lY', 'Sugar', '2.9', '0.816', '0', '-4.209', '1', '0.0465', '0.122', '0.0', '0.335', '0.557', '95.39', '0.548']
['6habFhsOp2NvshLv26DqMb', 'Despacito', '3.82', '0.797', '2', '-4.787', '1', '0.153', '0.198', '0.0', '0.067', '0.839', '177.928', '0.655']
['6XdYD0hrNIOHb0emKC3l9U', "Don't Stop Me Now", '7.05', '0.553', '5', '-5.51', '1', '0.0773', '0.71', '0.0', '0.101', '0.419', '112.603', '0.471']

In [ ]:
import pandas as pd
raw_data = pd.read_csv('Features.csv')

In [ ]:
raw_data

,id,name,duration,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,danceability
0,0VjIjW4GlUZAMYd2vXMi3b,Blinding Lights,3.33,0.730,1,-5.934,1,0.0598,0.00146,0.000095,0.0897,0.334,171.005,0.514
1,7qiZfU4dY1lWllzX7mPBI3,Shape of You,3.90,0.652,1,-3.183,0,0.0802,0.58100,0.000000,0.0931,0.931,95.977,0.825
2,2XU0oxnq2qxCpomAAuJY8K,Dance Monkey,3.49,0.588,6,-6.400,0,0.0924,0.69200,0.000104,0.1490,0.513,98.027,0.824
3,7qEHsqek33rTcFNT9PFqLf,Someone You Loved,3.04,0.405,1,-5.679,1,0.0319,0.75100,0.000000,0.1050,0.446,109.891,0.501
4,0e7ipj03S05BNilyu5bRzt,Rockstar,3.64,0.520,5,-6.136,0,0.0712,0.12400,0.000070,0.1310,0.129,159.801,0.585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5kqIPrATaCc2LqxVWzQGbk,7 Years,3.96,0.473,10,-5.829,1,0.0514,0.28700,0.000000,0.3910,0.340,119.992,0.765
96,3AJwUDP919kvQ9QcozQPxg,Yellow,4.45,0.661,11,-7.227,1,0.0281,0.00239,0.000121,0.2340,0.285,173.372,0.429
97,6UelLqGlWMcVH1E5c4H7lY,Sugar,2.90,0.816,0,-4.209,1,0.0465,0.12200,0.000000,0.3350,0.557,95.390,0.548
98,6habFhsOp2NvshLv26DqMb,Despacito,3.82,0.797,2,-4.787,1,0.1530,0.19800,0.000000,0.0670,0.839,177.928,0.655
99,6XdYD0hrNIOHb0emKC3l9U,Don't Stop Me Now,7.05,0.553,5,-5.510,1,0.0773,0.71000,0.000000,0.1010,0.419,112.603,0.471

In [ ]:
type(raw_data)

pandas.core.frame.DataFrame

In [ ]:
raw_data.shape

(100, 14)

In [ ]:
raw_data.isnull()

,id,name,duration,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,danceability
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
raw_data['name']

0       Blinding Lights
1          Shape of You
2          Dance Monkey
3     Someone You Loved
4              Rockstar
            ...
95              7 Years
96               Yellow
97                Sugar
98            Despacito
99    Don't Stop Me Now
Name: name, Length: 100, dtype: object

In [ ]:
# with the same output but different way
raw_data.name

0       Blinding Lights
1          Shape of You
2          Dance Monkey
3     Someone You Loved
4              Rockstar
            ...
95              7 Years
96               Yellow
97                Sugar
98            Despacito
99    Don't Stop Me Now
Name: name, Length: 100, dtype: object

In [ ]:
raw_data['tempo'].max()

186.003

In [ ]:
df2 = raw_data.loc[raw_data['tempo'].idxmax()]
df2

id                  7MXVkk9YMctZqd1Srtv4MB
name                               Starboy
duration                              3.84
energy                               0.587
key                                      7
loudness                            -7.015
mode                                     1
speechiness                          0.276
acousticness                         0.141
instrumentalness                  0.000006
liveness                             0.137
valence                              0.486
tempo                              186.003
danceability                         0.679
Name: 14, dtype: object

In [ ]:
raw_csv_data = pd.read_csv("Absenteeism-data.csv")

In [ ]:
type(raw_csv_data)

pandas.core.frame.DataFrame

In [ ]:
raw_csv_data

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [18]:
# copy initial data
df = raw_csv_data.copy()
df

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,11,26,07/07/2015,289,36,33,239.554,30,1,2,1,4
1,36,0,14/07/2015,118,13,50,239.554,31,1,1,0,0
2,3,23,15/07/2015,179,51,38,239.554,31,1,0,0,2
3,7,7,16/07/2015,279,5,39,239.554,24,1,2,0,4
4,11,23,23/07/2015,289,36,33,239.554,30,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
695,17,10,23/05/2018,179,22,40,237.656,22,2,2,0,8
696,28,6,23/05/2018,225,26,28,237.656,24,1,1,2,3
697,18,10,24/05/2018,330,16,28,237.656,25,2,0,0,8
698,25,23,24/05/2018,235,16,32,237.656,25,3,0,0,2
699,15,28,31/05/2018,291,31,40,237.656,25,1,1,1,2

In [19]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None